### ISSUE TITLE
[Natura] Bloodwood console errors

### ISSUE THREAD

**Issue by leonbaronick** [supermassimo/DynamicTrees-ExC#26]
I know that bloodwood can not be implemented, because of it growing upside down.

But while starting up the game, your mod causes some error messages to show up, even though bloodwood should just be ignored:

> [21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: java.io.FileNotFoundException: assets/dynamictreesnatura/trees/bloodwood.txt
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at com.ferreusveritas.dynamictrees.worldgen.JoCodeStore.addCodesFromFile(JoCodeStore.java:61)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at com.ferreusveritas.dynamictrees.trees.Species.addJoCodes(Species.java:1183)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at com.ferreusveritas.dynamictrees.trees.Species.<init>(Species.java:207)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at maxhyper.dynamictreesnatura.trees.TreeBloodwood$SpeciesBloodwood.<init>(TreeBloodwood.java:60)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at maxhyper.dynamictreesnatura.trees.TreeBloodwood.createSpecies(TreeBloodwood.java:227)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at com.ferreusveritas.dynamictrees.trees.TreeFamily.<init>(TreeFamily.java:110)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at maxhyper.dynamictreesnatura.trees.TreeBloodwood.<init>(TreeBloodwood.java:201)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at maxhyper.dynamictreesnatura.ModContent.registerBlocks(ModContent.java:159)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_172_ModContent_registerBlocks_Register.invoke(.dynamic)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[21:39:37] [Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.worldgen.JoCodeStore:addCodesFromFile:65]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[21:39:37] [Client thread/WARN] [FML]: ****************************************
[21:39:37] [Client thread/WARN] [FML]: * Registry Block: The object Block{dynamictreesnatura:bloodwoodbranch} has been registered twice for the same name dynamictreesnatura:bloodwoodbranch.
[21:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:300)
[21:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
[21:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
[21:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.registerAll(ForgeRegistry.java:154)
[21:39:37] [Client thread/WARN] [FML]: *  at maxhyper.dynamictreesnatura.ModContent.registerBlocks(ModContent.java:169)
[21:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_172_ModContent_registerBlocks_Register.invoke(.dynamic)...
[21:39:37] [Client thread/WARN] [FML]: ****************************************
[21:39:37] [Client thread/WARN] [FML]: ****************************************
[21:39:37] [Client thread/WARN] [FML]: * Registry Block: The object Block{dynamictreesnatura:fusewoodbranch} has been registered twice for the same name dynamictreesnatura:fusewoodbranch.
[21:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:300)
[21:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
[21:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
[21:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.registerAll(ForgeRegistry.java:154)
[21:39:37] [Client thread/WARN] [FML]: *  at maxhyper.dynamictreesnatura.ModContent.registerBlocks(ModContent.java:169)
[21:39:37] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_172_ModContent_registerBlocks_Register.invoke(.dynamic)...
[21:39:37] [Client thread/WARN] [FML]: ****************************************

The last message is not related to bloodwood, but I included it in case you are unaware of it.

**Comment by leonbaronick** [comment]
Just noticed, that the bloodwood seed is also registered twice:

> [21:39:38] [Client thread/WARN] [FML]: ****************************************
[21:39:38] [Client thread/WARN] [FML]: * Registry Item: The object maxhyper.dynamictreesnatura.items.ItemDynamicSeedBloodwood@57769305 has been registered twice for the same name dynamictreesnatura:bloodwoodseed.
[21:39:38] [Client thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:300)
[21:39:38] [Client thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
[21:39:38] [Client thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
[21:39:38] [Client thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.registerAll(ForgeRegistry.java:154)
[21:39:38] [Client thread/WARN] [FML]: *  at maxhyper.dynamictreesnatura.ModContent.registerItems(ModContent.java:227)
[21:39:38] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_171_ModContent_registerItems_Register.invoke(.dynamic)...
[21:39:38] [Client thread/WARN] [FML]: ****************************************

**Comment by supermassimo** [comment]
fixed in [1.0.1](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-natura/files/2999144)
